FROM bioconductor/release_base:latest
MAINTAINER Alexander Titus <alexander.j.titus.gr@dartmouth.edu>

RUN mkdir -p /scripts
ADD INSTALL.R /scripts/INSTALL.R

# Install R packages
# RUN Rscript "library("methods")"

# RUN Rscript INSTALL.R

# start app
# CMD [ "R" ]
